### ISSUE TITLE
BuildData_cuhk03.py

### ISSUE THREAD

**Issue by Zeros12** [cwhgn/MTDnet#1]
I am getting this error when I want to run your file "BuildData_cuhk03.py". Train and val images were created but there were following errors. Please advise regarding this issue.

Successfully load test data! Test data is  (100, 2)
cam_ratio: [728 367  65]
train: ids_tnum:1160,img_tnum=11219,pair_tnum=27115
total: ids_num:1360,img_num=13163,pair_num=31839
ids is 1160, CamA images is 5513, CamB images is 5706.
ids is 100, CamA images is 484, CamB images is 495.
ids is 100, CamA images is 474, CamB images is 491.
Traceback (most recent call last):
  File "BuildData_cuhk03.py", line 307, in <module>
    BuildTripleFile(indir,'train',1160)
  File "test.py", line 198, in BuildTripleFile
    pos1_list.write('%s 0\n' %list[x,0])
IndexError: index 0 is out of bounds for axis 1 with size 0

**Comment by cwhgn** [comment]
The indexError means that your "list" is null.
Maybe it caused by a wrong path ("indir") in BuildTripleFile(indir,'train',1160).
Or you can track the "list" in the BuildTripleFile function to see why it's null.
